export const ADD_VALUE = "ADD_VALUE";
export const REMOVE_TODO = "REMOVE_TODO";
export const SELECTED_FRUIT = "SELECTED_FRUIT";
export const SELECTED_FRUIT_PERSIST = "SELECTED_FRUIT_PERSIST";
export const RESET_PERSIST_STORE = "RESET_PERSIST_STORE";
export const GET_API_DATA = "GET_API_DATA";
export const GET_API_DATA_SUCCESS = "GET_API_DATA_SUCCESS";
export const GET_API_DATA_FAILURE = "GET_API_DATA_FAILURE";
